Repository VitorM3/Ecommerce-ED, pull requests merged in 2024-06, with the labels that each got.

#15 FEAT: Add Script sql
  database_base/database.sql
  database_base/docker-compose.yml
Labels: enhancement

#19 FEAT: Add system architecture
  README.md
  assets/System_Architecture.png
Labels: documentation

#20 feat: initial documentation
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  COLABORATORS.md
  CONTRIBUTING.md
  LICENSE
  README.md
  SECURITY.md
Labels: documentation, enhancement
